### ISSUE TITLE
三星s8这种手机，2960 x 1440适用吗？

### ISSUE THREAD

**Issue by cheng-peng** [ladingwu/dimens_sw#1]
现在有很多手机高度都特别高，就想这个手机就比平常手机高400像素，那这种适配可以适配吗？

**Comment by songsongtao** [comment]
我也想问这个问题,如果是全面屏手机,能适配吗

**Comment by QuincySx** [comment]
现在基本都是宽度适配，按高度放控件用百分比吧，如果高度用这种方式容易拉长

**Comment by ladingwu** [comment]
全面屏是高度拉长，我们的适配是以宽度为依据的，基本没什么影响

**Comment by ladingwu** [comment]
弄清楚这种适配原理，2960 x 1440分辨率完全可以适配，
