### ISSUE TITLE
（此问题不是bug）请问，这个框架在屏幕旋转时，处理过相关逻辑了吗？

### ISSUE THREAD

**Issue by baowenqing** [ladingwu/dimens_sw#12]
这两天在做屏幕适配，用的是今日头条的解决方案  应用是横屏的   但是在屏幕旋转后（锁屏，竖屏下解锁），fg中的recycleview中的item就会出现异常【图标变大，感觉是取了】（刚打开应用的时候都是正常的）
请问，咱们这个框架有这个问题吗？急，感谢回复

**Comment by ladingwu** [comment]
没有问题，你可以自行测试下，
