### ISSUE TITLE
能列出你项目中用的dpi目录吗

### ISSUE THREAD

**Issue by TopTime1** [ladingwu/dimens_sw#13]
300,320,360,411，450，这几个尺寸是比较必要的，还有其他的吗？

**Comment by TopTime1** [comment]
还有个问题，value里默认的dimens需要粘贴的是哪个目录下的

**Comment by ladingwu** [comment]
DP_sw__300(300),
	 DP_sw__320(320),
	 DP_sw__340(340),
	 DP_sw__350(350),
	 DP_sw__360(360),
	 DP_sw__370(370),
	 DP_sw__380(380),
	 DP_sw__390(390),
	 DP_sw__400(400),
	 DP_sw__411(411),
	 DP_sw__420(420),
	 DP_sw__440(440),
	 DP_sw__460(460),
	 DP_sw__480(480);

如果你担心漏掉，可以考虑以300-450之间，以10为步距，生成十几个文件，这样基本上万无一失了。

**Comment by TopTime1** [comment]
ok，多谢大佬
