### ISSUE TITLE
该方法对比分辨率适配的方法有什么异同？

### ISSUE THREAD

**Issue by liulianshanzhu** [ladingwu/dimens_sw#14]
我现在是在不同分辨率的dimens文件生成自己所需要的px，这种方法跟您所使用的方法有什么优劣吗？

**Comment by liulianshanzhu** [comment]
最终系统会将dp转为px，根据px = density * dp这个公式，density是能够自己调整的吗？

**Comment by ladingwu** [comment]
这个容错性好一些
