### ISSUE TITLE
TV适配有个问题

### ISSUE THREAD

**Issue by ghost** [ladingwu/dimens_sw#15]
我们设备信息:
宽:"1920px" 高 :1080px dpi:160
换算sw为(1920/(160/160))=1920

生成values-sw1920dp文件夹,我进去看了下
![image](https://user-images.githubusercontent.com/18097997/46060556-5def0200-c196-11e8-9453-b344c6bdb0ca.png)
我们设备 应该是1dp=1px的

**Comment by ladingwu** [comment]
这是设计稿的尺寸和真实尺寸的比值，而不是px和dp的比值

**Comment by ladingwu** [comment]
只要你参数填对了，适配就会OK
