### ISSUE TITLE
华为麦芒5手机计算出来的和实际使用的smallestWidth差这么多呢？

### ISSUE THREAD

**Issue by Destiny01** [ladingwu/dimens_sw#17]
![qq 20181128122506](https://user-images.githubusercontent.com/11342391/49129055-0fcabc00-f309-11e8-845c-11dbba597765.jpg)

**Comment by ladingwu** [comment]
是不是华为智能调整分辨率功能导致的

**Comment by ladingwu** [comment]
我现在在华为开发者平台里面测试了能用的所有手机，都是OK的，不过华为好像没有提供麦芒5，有麦芒6

**Comment by dariusz666777** [comment]
.
