### ISSUE TITLE
请问一下，这个项目怎么用呢？

### ISSUE THREAD

**Issue by panyy** [ladingwu/dimens_sw#2]

**Comment by ha6cc** [comment]
直接运行DimenGenerator下面的main方法，会在pc端生成/androidui/adapter目录下面有对接的dimens文件夹

**Comment by thsai** [comment]
生成在哪里？找不到。。。

**Comment by ha6cc** [comment]
运行这个类所在的磁盘根目录上会自动创建/androidui/adapter这个目录里面。如果想自己指定目录，就修改DimenGenerator.java文件中main方法中的MakeUtils.makeAll方法的最后一个参数。

**Comment by ladingwu** [comment]
@ha6cc 说得很清楚
