### ISSUE TITLE
DimenGenerator.main()没有生成文件

### ISSUE THREAD

**Issue by zhjun2016** [ladingwu/dimens_sw#21]
public void clickCreate(View view) {
        DimenGenerator.main();
    }

DimenGenerator文件，方法代码，
 public static void main(String[] args) {
        int smallest = DESIGN_WIDTH>DESIGN_HEIGHT? DESIGN_HEIGHT:DESIGN_WIDTH;  //     求得最小宽度
        DimenTypes[] values = DimenTypes.values();
        for (DimenTypes value : values) {
            File file = new File("");
            MakeUtils.makeAll(smallest, value, file.getAbsolutePath());
        }

    }
    public static void main() {
        int smallest = DESIGN_WIDTH>DESIGN_HEIGHT? DESIGN_HEIGHT:DESIGN_WIDTH;  //     求得最小宽度
        DimenTypes[] values = DimenTypes.values();
        for (DimenTypes value : values) {

            File file = new File("");
            MakeUtils.makeAll(smallest, value, file.getAbsolutePath());
        }

    }

调用DimenGenerator.main()没有生成文件

**Comment by ladingwu** [comment]
这个项目可以直接运行java工程的，建议你直接运行java工程代码即可，如果你运行在手机里面，那么文件就生成在手机项目的私有目录下了，你很难拿到
