### ISSUE TITLE
最小宽度计算与实际不一致

### ISSUE THREAD

**Issue by WaterElva** [ladingwu/dimens_sw#22]
这方案到底还能不能用？

dpi:320 width pixels : 1920
计算出来的smallestWidth: 960.0dp
实际使用的smallestWidth: 490dp

当前手机 ： HUAWEI BZT-W09
当前系统 ： 8.0.0

**Comment by WaterElva** [comment]
设计图 宽960 高600

**Comment by WaterElva** [comment]
屏幕分辨率 1920 * 1200

**Comment by WaterElva** [comment]
计算的最小宽度应该是600才对的吧，就算添加了values-sw600dp 它还是使用490

**Comment by 6cwong** [comment]
> 计算的最小宽度应该是600才对的吧，就算添加了values-sw600dp 它还是使用490

你这个是平板吧，分辨率是1920 * 1200 实际上最小宽度不会是1200，应该是1032，因为它会扣除底部虚拟导航键的高度，所以1032除以2约等于500，向下寻找，自然是490。

**Comment by ladingwu** [comment]
平板的width pixels好像取的有点问题，应该是我写的demo里面计算有点问题，适配方案是OK的

**Comment by ladingwu** [comment]
这个平板居然是横着用的。。。。

**Comment by 6cwong** [comment]
是的，你demo的计算有问题，比如分辨率是1920* 1200 的平板，无论是横着用还是竖着用，最小宽度就是1200，而demo中直接取dm.widthPixels这个应该不对，这个值会跟随横竖屏变化而变化。

**Comment by ladingwu** [comment]
@shunHuang 你说的对，我已经意识到这个问题了，刚提交了修改

**Comment by itgoyo** [comment]
@ladingwu ，老师你好，现在是2020-4-30,我在使用1920*1200平板的时候还是出现了
```
dpi:320 width pixels : 1200
计算出来的 smallestWidth: 600.0dp
实际使用的 smallestWidth: 490dp
```
看到了项目在 Apr 4, 2019 已经提交了修改，但是此时此刻项目跑起来还是没有实际使用正确，请问这个要怎么解决呢

**Comment by ladingwu** [comment]
> @ladingwu ，老师你好，现在是2020-4-30,我在使用1920*1200平板的时候还是出现了
> 
> ```
> dpi:320 width pixels : 1200
> 计算出来的 smallestWidth: 600.0dp
> 实际使用的 smallestWidth: 490dp
> ```
> 
> 看到了项目在 Apr 4, 2019 已经提交了修改，但是此时此刻项目跑起来还是没有实际使用正确，请问这个要怎么解决呢

看看开发者模式下，是否手动改过了最小宽度值？平板是原生系统么？是否刷过ROM?
