### ISSUE TITLE
大佬,问个问题可以生成负的么

### ISSUE THREAD

**Issue by zhangqifan1** [ladingwu/dimens_sw#28]

**Comment by MrFishC** [comment]
推荐看一篇文章先去了解一下如何使用ScreenMatch插件，https://www.jianshu.com/p/1302ad5a4b04;
了解后，接着在module（主或其它）下的 res/values/dimens.xml 中自定义内容模板，然后可以通过ScreenMatch插件生成,再结合该开源项目确定需要生成哪些values-swxxx目录。

**Comment by zhangqifan1** [comment]
大佬,-dpi 可以生成么 是在for循环那里 改0 么?

**Comment by MrFishC** [comment]
建议先了解一下ScreenMatch插件先，需要花一点时间去看一下的，不需要在ladingwu老师的项目的代码中更改，而是使用as中的插件，推荐的文章有ScreenMatch的详细用法，下面是我的项目中定义的木板。

`<?xml version="1.0" encoding="UTF-8"?>
<resources>

	<dimen name="status_bar_height">@dimen/dp_0</dimen>
	<dimen name="dp_m_60">-57.6000dp</dimen>　
	<dimen name="dp_m_30">-28.8000dp</dimen>　
	<dimen name="dp_m_20">-19.2000dp</dimen>　
	<dimen name="dp_m_12">-11.5200dp</dimen>　
	<dimen name="dp_m_10">-9.6000dp</dimen>　
	<dimen name="dp_m_8">-7.6800dp</dimen>　
	<dimen name="dp_m_5">-4.8000dp</dimen>　
	<dimen name="dp_m_2">-1.9200dp</dimen>　
	<dimen name="dp_m_1">-0.9600dp</dimen>　
	<dimen name="dp_0">0.0000dp</dimen>　
	<dimen name="dp_0_1">0.0960dp</dimen>　
	<dimen name="dp_0_5">0.4800dp</dimen>　
	<dimen name="dp_1">0.9600dp</dimen>　
	<dimen name="dp_1_5">1.4400dp</dimen>　
	<dimen name="dp_2">1.9200dp</dimen>　
	<dimen name="dp_2_5">2.4000dp</dimen>　
	<dimen name="dp_3">2.8800dp</dimen>　
	<dimen name="dp_3_5">3.3600dp</dimen>　
	<dimen name="dp_4">3.8400dp</dimen>　
	<dimen name="dp_4_5">4.3200dp</dimen>　
	<dimen name="dp_5">4.8000dp</dimen>　
	<dimen name="dp_6">5.7600dp</dimen>　
	<dimen name="dp_7">6.7200dp</dimen>　
	<dimen name="dp_7_5">7.2000dp</dimen>　
	<dimen name="dp_8">7.6800dp</dimen>　
	<dimen name="dp_9">8.6400dp</dimen>　
	<dimen name="dp_10">9.6000dp</dimen>　
	<dimen name="dp_11">10.5600dp</dimen>　
	<dimen name="dp_12">11.5200dp</dimen>　
	<dimen name="dp_13">12.4800dp</dimen>　
	
	<dimen name="dp_720">691.2000dp</dimen>　
	<dimen name="sp_6">5.7600sp</dimen>　
	<dimen name="sp_7">6.7200sp</dimen>　
	
	<dimen name="sp_42">40.3200sp</dimen>　
	<dimen name="sp_48">46.0800sp</dimen>　
</resources>
`

**Comment by zhangqifan1** [comment]
哈哈,谢谢,我搞出来了
