### ISSUE TITLE
android.view.InflateException: Binary XML file line #8: Binary XML file line #8: You must supply a layout_height attribute.

### ISSUE THREAD

**Issue by TopTime1** [ladingwu/dimens_sw#29]
现在友盟统计里有这种类似的报错，华为mate9，dpi373.3左右，
![image](https://user-images.githubusercontent.com/7701170/68726829-a5845780-05fd-11ea-8527-4bb56141c34d.png)
目录里有370为什么还会报这个错

**Comment by ladingwu** [comment]
你的xml布局控件里面必须由layout_height，layout_width这两个属性
