### ISSUE TITLE
生成适配文件失败

### ISSUE THREAD

**Issue by LiXiangMaster** [ladingwu/dimens_sw#3]
为啥在代码中调用 markAll方法传入res的路径后，生成不了适配文件报java.io.FileNotFoundException: /dimen/values-sw360dp/dimens.xml (No such file or directory)异常呢

**Comment by ladingwu** [comment]
有其他信息么？我无法判断到底哪里除了问题？，或者生成路径你写绝对地址，然后提前判断文件是否生成？

**Comment by JimmyRoad** [comment]
我这生成对的，直接使用你这项目默认的路径。@ladingwu 攻守兼备，SO COOL

**Comment by simplepeng** [comment]
@lixiangxiaoling 
public static void main(String[] args) {

        DimenTypes[] values = DimenTypes.values();
        for (DimenTypes value : values) {
            MakeUtils.makeAll(DESIGN_WIDTH, value, new File("").getAbsolutePath());
        }

    }
