### ISSUE TITLE
测试后发现并没有适配成功

### ISSUE THREAD

**Issue by yang-zw** [ladingwu/dimens_sw#4]
以设计稿,1280*720为基准.生成了SW150~400的适配文件夹. 然后运行在640*960,320*480,720*1280的机型上.出现完全不同的适配效果

XML代码如下
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    tools:context=".IdCardActivity">

    <android.support.constraint.Guideline
        android:id="@+id/guideline"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        app:layout_constraintGuide_percent="0.5" />

    <ImageView
        android:id="@+id/imageView"
        android:layout_width="@dimen/qb_px_280"
        android:layout_height="@dimen/qb_px_280"
        android:layout_marginLeft="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="@dimen/qb_px_200"
        android:src="@drawable/wechat_code"
        app:layout_constraintEnd_toStartOf="@+id/guideline"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <ImageView
        android:layout_width="@dimen/qb_px_280"
        android:layout_height="@dimen/qb_px_280"
        android:layout_marginEnd="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginTop="@dimen/qb_px_200"
        android:src="@drawable/qq_code"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="@+id/guideline"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/textView2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/qb_px_50"
        android:text="售后微信"
        app:layout_constraintEnd_toStartOf="@+id/guideline"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/imageView" />

    <TextView
        android:id="@+id/textView4"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="售后QQ"
        app:layout_constraintBaseline_toBaselineOf="@+id/textView2"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="@+id/guideline" />

    <TextView
        android:id="@+id/textView5"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="111111111111"

        android:textColor="#333"
        app:layout_constraintEnd_toStartOf="@+id/guideline"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView2" />

    <TextView
        android:id="@+id/textView6"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="222222222222"
        android:textColor="#333"
        app:layout_constraintBaseline_toBaselineOf="@+id/textView5"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="@+id/guideline" />

    <android.support.constraint.Guideline
        android:id="@+id/guideline2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        app:layout_constraintGuide_percent="0.5" />

    <TextView
        android:id="@+id/textView7"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/qb_px_50"
        android:text="电话: "
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView5" />

    <TextView
        android:id="@+id/textView8"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="123123123123"
        android:textColor="#333"
        app:layout_constraintBaseline_toBaselineOf="@+id/textView7"
        app:layout_constraintEnd_toStartOf="@+id/guideline"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toEndOf="@+id/textView7" />

    <TextView
        android:id="@+id/textView9"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="手机: "
        android:layout_marginTop="@dimen/qb_px_50"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView7" />

    <TextView
        android:id="@+id/textView11"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="123123123123"
        android:textColor="#333"
        app:layout_constraintBaseline_toBaselineOf="@+id/textView9"
        app:layout_constraintEnd_toStartOf="@+id/guideline"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toEndOf="@+id/textView9" />

    <TextView
        android:id="@+id/textView13"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="售后地址: "
        android:layout_marginTop="@dimen/qb_px_50"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView9" />

    <TextView
        android:id="@+id/textView14"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:text="广州市天河区广州市天河区广州市天河区"
        android:textColor="#333"
        android:textSize="@dimen/qb_px_40"
        app:layout_constraintBaseline_toBaselineOf="@+id/textView13"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toEndOf="@+id/textView13" />

</android.support.constraint.ConstraintLayout>`

从左到右依次是:640*960,320*480,720*1280.其中720*1280和AS预览图保持一致,适配成功.另外两个不行
效果图
![qq 20180626100739](https://user-images.githubusercontent.com/24226199/41885130-211ea002-7929-11e8-8090-12cfa0ed71b9.jpg)

**Comment by ladingwu** [comment]
如果系统版本号在4.0以上的化，其实是已经适配成功了的，只不过在高这个维度你应该设计成可滑动的哦，因为明显高度超出了

**Comment by yang-zw** [comment]
这么说这个方案只适合左右边距的适配吗? 如果是上下距离用这个单位是不行的

**Comment by ladingwu** [comment]
上下边距也能用的，但是你要考虑根布局的的长度问题，特别是图中的手机尺寸不太常见了，所以你需要考虑把根布局设计成可滑动的情况才行，其实图中能够看到，UI还原度是比较一致的。

Android的手机的布局都是以宽度为基准，高这个维度依照情况设计成可滑动的。

**Comment by yang-zw** [comment]
好的，谢谢你的回复
