### ISSUE TITLE
你好关于设计稿尺寸填入的问题

### ISSUE THREAD

**Issue by gyyak46** [ladingwu/dimens_sw#6]
private static final int DESIGN_WIDTH = 375;  这个375是怎么得到的
如果我的屏幕宽度是1080 DESIGN_WIDTH 这个值应该是多少
谢谢

**Comment by ladingwu** [comment]
这个是你们的设计师的设计图的宽度，

**Comment by marren06** [comment]
设计图的宽度是px还是dp，有的公司设计图上面标注的dp,我也不懂这个是dp还是px?
  /**
     * 设计稿尺寸(将自己设计师的设计稿的宽度填入)
     */
    private static final int DESIGN_WIDTH = 375;

    /**
     * 设计稿的高度  （将自己设计师的设计稿的高度填入）
     */
    private static final int DESIGN_HEIGHT = 667;


这两个值怎么得到的？  还是说就是设计师按照1080*1920设计  ，DESIGN_WIDTH =1080，DESIGN_HEIGHT =1920？？？
