### ISSUE TITLE
关于华为P系列的一些手机无法适配

### ISSUE THREAD

**Issue by zzh1026** [ladingwu/dimens_sw#7]
我们这边有个华为P9Plus手机, 然后使用dp适配在这个手机上不起作用,测试代码为
`
<TextView
        android:layout_width="@dimen/dp_360"
        android:layout_height="@dimen/dp_20"
        android:layout_marginTop="@dimen/dp_15"
        android:background="#f00" />

    <TextView
        android:layout_width="180dp"
        android:layout_height="@dimen/dp_20"
        android:layout_marginTop="@dimen/dp_15"
        android:background="#00f" />

    <TextView
        android:layout_width="180dp"
        android:layout_height="@dimen/dp_20"
        android:layout_gravity="right"
        android:background="#f0f" />

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_40"
        android:layout_marginTop="@dimen/dp_15"
        android:gravity="center_vertical">

        <TextView
            android:layout_width="@dimen/dp_180"
            android:layout_height="@dimen/dp_30"
            android:background="#f00" />

        <TextView
            android:layout_width="@dimen/dp_180"
            android:layout_height="@dimen/dp_15"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:background="#00f" />

    </RelativeLayout>
`
在小米8手机上没问题,但是在华为手机上却表现的完全一致而且完全没有适配, 项目中有sw430dp的适配,结果出来确实默认value中的值,就是说sw适配的时候没起作用,这是怎么回事?请问大神有碰到过吗?

**Comment by ladingwu** [comment]
你可以测试下手机的宽度dp值是多少，

**Comment by ladingwu** [comment]
是P系列都不行么？ 可否给出截图？

**Comment by ladingwu** [comment]
目前手边的P9 ,navo 是没有问题的，按理说，这个和系统有关，同一个厂商的手机应该不会出现部分有问题的现象

**Comment by zzh1026** [comment]
测试过了, 这款p9plus手机的宽是432dp , 宽1080px , 系统的 dpi 值为 2.5. 
但是实际用的时候他的dpi值取得3 ,所以按照宽为 360来加载,所以实际上有偏差了, 主要问题是 为什么 系统获取到的 1dp = 2.5px , 加载时候却按照 1pd = 3px 来计算了....
![Uploading 274250070451524645.png…]()

**Comment by zzh1026** [comment]
![274250070451524645](https://user-images.githubusercontent.com/16069210/43693465-98532844-9960-11e8-8fc5-b91cf469cc74.png)

**Comment by ladingwu** [comment]
实际用的时候他的dpi值取得3是什么意思？是不是系统最终是在sw-360文件夹下去获取dimens文件相关的值？按照你的数据，densityDpi的值是400 是吧？

**Comment by ladingwu** [comment]
你可以直接给我发邮件851547570@qq.com

**Comment by ArtisanM** [comment]
同问

**Comment by ladingwu** [comment]
据说华为手机可以手动调节最小宽度dp值？开发者选项里面？？

**Comment by badboy-tian** [comment]
所以各位大佬,  谁有华为的破手机测试下?  我手里没有

**Comment by Destiny01** [comment]
https://deveco.huawei.com/remotetest/devices/ 华为远程真机测试，我用着没啥问题！你们可以用用华为的测试试试！

**Comment by Destiny01** [comment]
在华为麦芒5手机确实显示上不太精确

**Comment by ladingwu** [comment]
> 在华为麦芒5手机确实显示上不太精确

显示不精确往往是没有命中对应的尺寸，只能向下兼容，找一个接近的尺寸文件，就会导致还原度下降

**Comment by ladingwu** [comment]
> 在华为麦芒5手机确实显示上不太精确

能否把出问题的手机的测试过程发给我看看？   我的邮箱851547570@qq.com

**Comment by Destiny01** [comment]
![screenshot_2018-09-28-16-33-48](https://user-images.githubusercontent.com/11342391/46197625-f1face00-c33c-11e8-9da9-e62293c08e3f.png)

这个最小宽度算出来应该是1080 / 2.75 = 392.7，应该使用sw-392dp的dimens吧！
