### ISSUE TITLE
这个java工程不能在mac上吗运行吗？

### ISSUE THREAD

**Issue by shixl** [ladingwu/dimens_sw#9]
运行的时候会一直提示文件夹找不到

**Comment by chenwentong0** [comment]
MakeUtils.makeAll(DESIGN_WIDTH, value, new File("").getAbsolutePath()+"/app/src/main/res/");我的文件路径是这样写的可以生成

**Comment by ladingwu** [comment]
嗯，如果文件夹不存在，可以尝试先创建
